<?php
/*SELECT * INTO OUTFILE "/tmp/parking.cvs"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY "\n"
FROM parking;

SELECT * INTO OUTFILE "/tmp/payout.cvs"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY "\n"
FROM payout;

SELECT * INTO OUTFILE "/tmp/payout_transaction.cvs"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY "\n"
FROM payout_transaction;

SELECT * INTO OUTFILE "/tmp/user.cvs"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY "\n"
FROM user;

SELECT * INTO OUTFILE "/tmp/parking_types.cvs"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY "\n"
FROM parking_type; */