<?php

use yii\db\Migration;

class m171025_151750_user_assign_admin extends Migration
{

	/**
	 * @var
	 */
	public $permission;

	/**
	 * @var
	 */
	public $rows;

	/**
	 *
	 */
	public function init() {
		$this->permission = \Yii::$app->authManager->getRole('admin');
		$this->rows = (new \yii\db\Query())->select(['id'])->from('{{%user}}')->all();

		parent::init(); // TODO: Change the autogenerated stub
	}

	public function safeUp() {
		foreach ($this->rows as $item) {
			\Yii::$app->authManager->assign($this->permission, $item['id']);
		}
	}

	public function safeDown() {
		foreach ($this->rows as $item) {
			\Yii::$app->authManager->revoke($this->permission, $item['id']);
		}
	}
}
