<?php
/**
 * @author Andru Cherny <acherny@minexsystems.com>
 * Date: 19.10.17
 * Time: 17:51
 */
declare(strict_types=1);

namespace tests\unit\Modules\User\Workers;

use App\Modules\User\Workers\UserRPC;
use tests\unit\BaseTestCase;

/**
 * Class UserRPCTest
 * @package tests\unit\Modules\User\Workers
 */
class UserRPCTest  extends BaseTestCase
{

	/**
	 * @var UserRPC
	 */
	public $testedClass = UserRPC::class;

	public function _before() {
		$reflection = new \ReflectionClass($this->testedClass);
		$this->testedClass = $reflection->newInstanceWithoutConstructor();
		parent::_before(); // TODO: Change the autogenerated stub
	}

	public function testGetTotalUsers() {
		$totalUser = $this->testedClass->getTotalUsers();
		$this->assertInternalType('int', $totalUser);
	}
}